[package]
name = "rusty-paper"
authors = ["Saeed Andalib <saeedandalib5@gmail.com>"]
description = "Personal blog backend."
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["blog", "weblog"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rustypaper"
path = "src/lib/lib.rs"

[dependencies]
