version: "3"

services:
  db:
    image: postgres:15

    expose:
      - "5432"

    ports:
      - "5432:5432"

    volumes:
      - backend-db-dev:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: ${RUSTYPAPER_DATABASE_PASSWORD}
      POSTGRES_USER: ${RUSTYPAPER_DATABASE_USER}
      POSTGRES_DB: ${RUSTYPAPER_DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data

    networks:
      - backend-dev


  backend:
    build: .

    ports:
      - "3000:3000"

    expose:
      - "3000"

    volumes:
      - .:/urs/src/app

    depends_on:
      - db

    env_file:
      - ".env"

    environment:
      DATABASE_URL: postgres://${RUSTYPAPER_DATABASE_USER}:${RUSTYPAPER_DATABASE_PASSWORD}@db:5432/${RUSTYPAPER_DATABASE_NAME}
      RUSTYPAPER_DATABASE_HOST: db

    networks:
      - backend-dev


volumes:
  backend-db-dev: {}

networks:
  backend-dev: {}